# Generated by Django 4.2.4 on 2023-09-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateField(verbose_name='Inicio Campeonato')),
                ('fecha_fin', models.DateField(verbose_name='Fin Campeonato')),
                ('restriccion', models.CharField(max_length=500, verbose_name='Principal Restriccion')),
            ],
        ),
        migrations.CreateModel(
            name='Dirigentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=200)),
                ('campeonato_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
            ],
        ),
    ]
