# Generated by Django 4.2.4 on 2023-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_alter_dirigentes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='lugar',
            field=models.CharField(default='', max_length=500),
        ),
    ]
