# Generated by Django 4.2.4 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_campeonato_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirigentes',
            name='campeonato_asociado',
        ),
        migrations.AddField(
            model_name='dirigentes',
            name='campeonato_asociado',
            field=models.ManyToManyField(to='campeonato.campeonato'),
        ),
    ]
