# Generated by Django 4.2.4 on 2023-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='goles_max',
            field=models.IntegerField(default=0),
        ),
    ]
