# Generated by Django 4.2.4 on 2023-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_jugadores_goles_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ManyToManyField(to='equipos.equipo')),
            ],
        ),
    ]
