# Generated by Django 4.2.4 on 2023-09-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='goles_ganador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='goles_perdedor',
            field=models.IntegerField(default=0),
        ),
    ]
