# Generated by Django 4.2.4 on 2023-10-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_grupo_equipos'),
        ('encuentros_equipos', '0002_resultado_goles_ganador_resultado_goles_perdedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='goles_local',
            field=models.IntegerField(default=0, verbose_name='goles_local'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='goles_visitante',
            field=models.IntegerField(default=0, verbose_name='goles_visitante'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.grupo'),
        ),
        migrations.DeleteModel(
            name='resultado',
        ),
    ]
