# Generated by Django 4.2.4 on 2023-09-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0004_grupo_nombre'),
        ('campeonato', '0004_remove_dirigentes_campeonato_asociado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeriaDirigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.dirigentes')),
            ],
        ),
    ]
