# Generated by Django 4.2.4 on 2023-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeriadirigente',
            name='archivo',
            field=models.FileField(blank=True, upload_to='uploads/Documentos/%Y/%m/%d/'),
        ),
    ]
